export const data = () => { [
  {
    "id": "0HXtCo0667hgmfjw7mR1",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 12:01:45 am",
    "sellingPrice": "₹58",
    "condition": "Drizzle",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "light intensity drizzle",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.95,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "cTrpCHHnNeqtpssnziXU",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 1:00:20 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.37,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "PrGjTUNcmAfCnIHW0e2d",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 2:00:23 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "overcast clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.06,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "Pos5FVUipBzVcUNeivOr",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 3:00:24 am",
    "sellingPrice": "₹58",
    "condition": "Drizzle",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "light intensity drizzle",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.37,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "cwSelqyvzu7WtmG5we8V",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 4:00:17 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.04,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "c4DeLTOxYb8CnNVWvVPY",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 5:00:17 am",
    "sellingPrice": "₹58",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "light rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.04,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "B7sA5Urnr60S2DyJcBtN",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 6:00:28 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 20.47,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "ThN8kqu5y2bJWx8fgK6M",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 7:02:21 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 20.63,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "0hZnmfdDkudPYyxU0g2r",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 7:03:27 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 20.63,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "ne42TOpnlLKFnWuDDi4b",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 8:00:20 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.37,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "4MWCorRK5fG3T5sCUZO7",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 9:00:27 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 22.27,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "ovnyQDoxiWlEOtvvWctK",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 10:00:32 am",
    "sellingPrice": "₹58",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 23.17,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "YECy8jseO6AthlEEbupy",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 11:00:32 am",
    "sellingPrice": "₹58",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "moderate rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 25.82,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "FJHiafRRpT96IJULZAm7",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 12:00:36 pm",
    "sellingPrice": "₹58",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "light rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 25.93,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "0kZSu4S3QQ5KArQpn8TL",
    "discountPercentage": "40% Off",
    "createdAt": "7/8/2024, 1:01:21 pm",
    "sellingPrice": "₹58",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹58",
    "weatherDescription": "light rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 26.59,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "1XFVahpkg0nkIvHXbkI1",
    "discountPercentage": "38% Off",
    "createdAt": "7/8/2024, 2:00:25 pm",
    "sellingPrice": "₹60",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "light rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 26.38,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "5OsqYFo5GrUwz3yaPfYk",
    "discountPercentage": "38% Off",
    "createdAt": "7/8/2024, 3:00:22 pm",
    "sellingPrice": "₹60",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "moderate rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 26.1,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "uTzrXDN6LF7trZO7CpzM",
    "discountPercentage": "38% Off",
    "createdAt": "7/8/2024, 4:00:29 pm",
    "sellingPrice": "₹60",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "moderate rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 25.85,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "1pCxu6Lqv9uTAqq81KIo",
    "discountPercentage": "38% Off",
    "createdAt": "7/8/2024, 5:00:19 pm",
    "sellingPrice": "₹60",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "light rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 24.4,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "eDy0NOKOBRbTGvIUYl0H",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "7/8/2024, 9:00:23 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 22.59,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "pNlAzcaQVosRfX6ud0QL",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "7/8/2024, 10:01:45 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 22.43,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "98n4ZZptH53F4yjNsHFj",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "7/8/2024, 10:03:49 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 22.43,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "GYFEs3vK3jqDZYIoJV45",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "7/8/2024, 11:00:15 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 22.43,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "28ezjUhXHamRx2q1yGbG",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "8/8/2024, 12:00:19 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 22.27,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "KUVIiRn4EXNbc2Z2aFYt",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "8/8/2024, 1:00:15 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.95,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "7VC4yA8ug7SqNE86yk1M",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "8/8/2024, 2:00:42 am",
    "sellingPrice": "₹60",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "light rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.95,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "Z9FujD32oSAtdAQ50E8y",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "8/8/2024, 3:00:18 am",
    "sellingPrice": "₹60",
    "condition": "Rain",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "moderate rain",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.95,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "V4z1NGTHZjs5zcy2PBU4",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "8/8/2024, 4:00:16 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.95,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "P7joSzJ0SCrQGuvr75mT",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "8/8/2024, 5:00:39 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "overcast clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.06,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "Ly6f5UPSfiGFRXaNGgkg",
    "discountPercentage": "Out of Stock38% Off",
    "createdAt": "8/8/2024, 6:00:16 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "overcast clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 20.78,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "cR0swXYcuBjrJtQueP4E",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 7:00:18 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.37,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "nDqSdK81ZvngHIAIumQL",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 8:00:21 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "overcast clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 21.06,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "xU8k5cz2V9XofIt4cKBH",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 9:00:27 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "broken clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 22.27,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "Wr9asgGZx9p3mcOKTAuZ",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 10:00:20 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 23.5,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "EtSpsC4w3tFUIWghzgwF",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 11:00:50 am",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 24.77,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "rV7w4Rhl7FOXHU17BaAp",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 12:00:45 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 25.35,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "4OBFks2U7t4mFFADW9hE",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 12:05:00 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 25.35,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "LV1iDPvrncYDA2SnlsFo",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 12:07:57 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 25.55,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "L9zmlSgWyYD5BZR5dkgA",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 1:00:29 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 26.51,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "bABIt9jCEIBVpV6hhL7o",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 2:00:32 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 26.72,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "oZyRhrfRpAFyokL2XSJh",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 3:00:28 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 26.9,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  },
  {
    "id": "CkRIzK0NHnu6l69Ekzhn",
    "discountPercentage": "38% Off",
    "createdAt": "8/8/2024, 4:00:24 pm",
    "sellingPrice": "₹60",
    "condition": "Clouds",
    "quantity": "1 kg",
    "discountedPrice": "₹60",
    "weatherDescription": "scattered clouds",
    "imageUrl": "https://cdn.zeptonow.com/production///tr:w-600,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/3383b1f8-c1be-4e07-ad30-74418513f8fc.jpeg",
    "temperature": 27.21,
    "description": "Description : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days\nDescription : Onions are high in nutrients and have been linked to a variety of health benefits such as enhanced heart health, better blood sugar control, and greater bone density.\nCountry of Origin : India\nShelf Life : 6 days",
    "title": "Onion",
    "url": "https://www.zeptonow.com/pn/onion/pvid/2f6630cd-3d48-4ac8-9905-1cf2acf28ec7"
  }
]; };